version: '3'

services:
  movies-neo4j-cron:
    build: ./data-cron-loader
    container_name: movies-neo4j-cron
    restart: unless-stopped
    volumes:
      - ./volumes/shared-data-to-load:/shared-data-to-load
    depends_on:
      - "movies-neo4j"
    environment:
      - GIT_REPO
      - NEO4J_AUTH
      - NEO4J_BOLT_URL=neo4j://movies-neo4j:7687
  
  movies-neo4j:
    image: neo4j:4.2.3
    container_name: movies-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474 # interface web du backoffice
      - 7687:7687 # api du backoffice (bolt)
    volumes:
      - ./volumes/neo4j-database:/data
      - ./volumes/shared-data-to-load:/shared-data-to-load:ro
    environment:
      - NEO4J_AUTH
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science", "n10s"]
      - NEO4J_dbms_unmanaged__extension__classes=semantics.extension=/rdf
