version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.35-bundle
    links:
      - mysql
    ports:
      # CONFIG - Change the 8181 here to expose Wikibase & MediaWiki on a different port
      - "8181:80"
    volumes:
      - ./volumes/mediawiki-images-data:/var/www/html/images
      - ./volumes/quickstatements-data:/quickstatements/data
    depends_on:
      - mysql
      - elasticsearch
    restart: unless-stopped
    networks:
      default:
        aliases:
          - wikibase.svc
          # CONFIG - Add your real wikibase hostname here, only for internal names and when NOT terminating SSL outside the container.
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
      - MW_SITE_NAME
      - MW_SITE_LANG
      - MW_ADMIN_NAME
      - MW_ADMIN_PASS
      - MW_ADMIN_EMAIL
      - MW_WG_SECRET_KEY
      - DB_USER
      - DB_PASS
      - DB_NAME


  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ./volumes/mediawiki-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # CONFIG - Change the default values in .env
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      default:
        aliases:
          - mysql.svc


  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    restart: unless-stopped
    ports:
      # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
      - "8282:80"
    depends_on:
      - wdqs-proxy
    networks:
      default:
        aliases:
          - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
      - LANGUAGE
      - BRAND_TITLE


  wdqs:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    volumes:
      - ./volumes/query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
          - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999


  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
      - "8989:80"
    depends_on:
      - wdqs
    networks:
      default:
        aliases:
          - wdqs-proxy.svc


  wdqs-updater:
    image: wikibase/wdqs:0.3.40
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
      - wdqs
      - wikibase
    networks:
      default:
        aliases:
          - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999


  elasticsearch:
    image: wikibase/elasticsearch:6.5.4-extra
    restart: unless-stopped
    networks:
      default:
        aliases:
          - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

