version: '3'

services:
  movies-cron:
    build: .
    container_name: movies-cron
    restart: unless-stopped
    volumes:
      - ./volumes/shared-data-to-load:/shared-data-to-load
    depends_on:
      - "movies-neo4j"
    environment:
      - GIT_REPO
      - NEO4J_BASE_URL
      - NEO4J_AUTH
  
  movies-neo4j:
    image: neo4j:4.2.3
    container_name: movies-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474 # interface web du backoffice
      - 7687:7687 # api du backoffice (bolt)
    expose:
      - "7474"
    volumes:
      - ./volumes/neo4j-database:/data
      - ./volumes/shared-data-to-load:/shared-data-to-load:ro
    environment:
      - NEO4J_AUTH
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
