version: '3'

services:

  movies-neo4j:
    image: neo4j:4.2.3
    container_name: movies-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474 # interface web du backoffice
      - 7687:7687 # api du backoffice (bolt)
    volumes:
      - ./volumes/data:/data
    environment:
      - NEO4J_AUTH # valeur secrete définie dans .env
#      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_connector_bolt_advertised__address=:7687

      # plugins pas forcément nécessaires (héritages de sudoc21)
      # https://neo4j.com/labs/apoc/4.1/introduction/
      # https://neo4j.com/docs/graph-data-science/current/introduction/
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
